//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutesList_cli.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceProject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceProject() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoutesList_cli.Resources.ResourceProject", typeof(ResourceProject).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple MSBuild project files found in &apos;{projectPath}&apos;. .
        /// </summary>
        internal static string Error_MultipleProjectsFound {
            get {
                return ResourceManager.GetString("Error_MultipleProjectsFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find a MSBuild project file in &apos;{projectPath}&apos;..
        /// </summary>
        internal static string Error_NoProjectsFound(object projectPath)
            => string.Format(Culture, GetResourceString("Error_NoProjectsFound", new[] { "projectPath" }), projectPath);

        /// <summary>
        ///   Looks up a localized string similar to The project file &apos;{path}&apos; does not exist..
        /// </summary>
        internal static string Error_ProjectPath_NotFound(object projectPath)
            => string.Format(Culture, GetResourceString("Error_ProjectPath_NotFound", new[] { "projectPath" }), projectPath);

        /// <summary>
        ///   Looks up a localized string similar to Cannot specify both &apos;--quiet&apos; and &apos;--verbose&apos; options..
        /// </summary>
        internal static string Error_QuietAndVerboseSpecified {
            get {
                return ResourceManager.GetString("Error_QuietAndVerboseSpecified", resourceCulture);
            }
        }

        internal static string Error_NoProjectNameFound(object projectPath)
            => string.Format(Culture, GetResourceString("Error_NoProjectNameFound", new[] { "projectPath" }), projectPath);

        internal static string GetResourceString(string resourceKey, string defaultValue = null) => ResourceManager.GetString(resourceKey, Culture);

        private static string GetResourceString(string resourceKey, string[] formatterNames)
        {
            var value = GetResourceString(resourceKey);
            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }
            return value;
        }
    }
}
