name: Codacy Coverage Reporter

on:
  workflow_run:
    workflows: [Net RoutesList CI]
    types:
      - completed

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ github.workspace }}/coverage/coverage1.xml, ${{ github.workspace }}/coverage/coverage2.xml, ${{ github.workspace }}/coverage/coverage3.xml, ${{ github.workspace }}/coverage/coverage4.xml, ${{ github.workspace }}/coverage/coverage5.xml, ${{ github.workspace }}/coverage/coverage6.xml